"""update section part

Revision ID: 5d4daa1f7e29
Revises: c0f022b91964
Create Date: 2024-06-28 11:19:07.650695

"""

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = "5d4daa1f7e29"
down_revision = "c0f022b91964"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "construction_section", sa.Column("has_sensor", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("construction_section", "has_sensor")
    # ### end Alembic commands ###
