"""fix tables

Revision ID: daad2f231ce8
Revises: a1043a3cf03f
Create Date: 2024-05-12 22:14:26.279988

"""

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = "daad2f231ce8"
down_revision = "a1043a3cf03f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("building_info", sa.Column("object_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("building_info", "object_id")
    # ### end Alembic commands ###
