"""update ondelete

Revision ID: a2b54cef67de
Revises: 85b9c4a015c1
Create Date: 2024-06-03 22:46:50.690879

"""

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = "a2b54cef67de"
down_revision = "85b9c4a015c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("construction_part_building_info_id_fkey", "construction_part", type_="foreignkey")
    op.create_foreign_key(None, "construction_part", "building_info", ["building_info_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint("construction_section_construction_part_id_fkey", "construction_section", type_="foreignkey")
    op.create_foreign_key(
        None, "construction_section", "construction_part", ["construction_part_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "construction_section", type_="foreignkey")
    op.create_foreign_key(
        "construction_section_construction_part_id_fkey",
        "construction_section",
        "construction_part",
        ["construction_part_id"],
        ["id"],
    )
    op.drop_constraint(None, "construction_part", type_="foreignkey")
    op.create_foreign_key(
        "construction_part_building_info_id_fkey", "construction_part", "building_info", ["building_info_id"], ["id"]
    )
    # ### end Alembic commands ###
