"""update ondelete for group

Revision ID: c0f022b91964
Revises: a2b54cef67de
Create Date: 2024-06-03 22:56:22.300333

"""

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = "c0f022b91964"
down_revision = "a2b54cef67de"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_group_group_id_fkey", "user_group", type_="foreignkey")
    op.drop_constraint("user_group_user_id_fkey", "user_group", type_="foreignkey")
    op.create_foreign_key(None, "user_group", "group", ["group_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "user_group", "user", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_group", type_="foreignkey")
    op.drop_constraint(None, "user_group", type_="foreignkey")
    op.create_foreign_key("user_group_user_id_fkey", "user_group", "user", ["user_id"], ["id"])
    op.create_foreign_key("user_group_group_id_fkey", "user_group", "group", ["group_id"], ["id"])
    # ### end Alembic commands ###
