"""init

Revision ID: 5f3619cbb41f
Revises:
Create Date: 2024-04-16 08:02:51.412257

"""

from uuid import uuid4
from alembic import op
import sqlalchemy as sa
from fastapi_users.password import PasswordHelper
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision = "5f3619cbb41f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_group_description"), "group", ["description"], unique=True)
    op.create_index(op.f("ix_group_id"), "group", ["id"], unique=False)
    op.create_index(op.f("ix_group_name"), "group", ["name"], unique=True)
    user_table = op.create_table(
        "user",
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("middle_name", sa.String(), nullable=True),
        sa.Column("mobile_phone", sa.String(), nullable=True),
        sa.Column("role", sa.Enum("ENGINEER", "CHIEF_ENGINEER", name="аccountrole"), nullable=False),
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "user_group",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "group_id"),
    )
    # ### end Alembic commands ###

    user_email = "admin@example.com"
    user_password = "initialPassword123"

    op.bulk_insert(
        user_table,
        [
            {
                "id": str(uuid4()),
                "role": "ENGINEER",
                "first_name": "Admin",
                "last_name": "Admin",
                "middle_name": "Admin",
                "mobile_phone": "+79991234567",
                "email": user_email,
                "hashed_password": PasswordHelper().hash(user_password),
                "is_active": True,
                "is_superuser": True,
                "is_verified": True,
            },
        ],
    )

    print(f"Admin account: email['{user_email}'] password['{user_password}']")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_group")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_group_name"), table_name="group")
    op.drop_index(op.f("ix_group_id"), table_name="group")
    op.drop_index(op.f("ix_group_description"), table_name="group")
    op.drop_table("group")
    # ### end Alembic commands ###
