"""added building info tables

Revision ID: a1043a3cf03f
Revises: 5f3619cbb41f
Create Date: 2024-05-12 21:33:06.280463

"""

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a1043a3cf03f"
down_revision = "5f3619cbb41f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "building_info",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("construction_type", sa.Integer(), nullable=True),
        sa.Column("construction_duration", sa.Float(), nullable=True),
        sa.Column("address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("technical_indicators", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("document_artifacts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "construction_part",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("object_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("power_indicators", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("technical_indicators", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("energy_efficiency", sa.String(), nullable=True),
        sa.Column("fire_danger_category", sa.String(), nullable=True),
        sa.Column("people_permanent_stay", sa.String(), nullable=True),
        sa.Column("responsibility_level", sa.String(), nullable=True),
        sa.Column("building_info_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["building_info_id"],
            ["building_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "construction_section",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("bim_artifacts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("construction_part_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["construction_part_id"],
            ["construction_part.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("user", "first_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "last_name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "last_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "first_name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_table("construction_section")
    op.drop_table("construction_part")
    op.drop_table("building_info")
    # ### end Alembic commands ###
