"""update table build_info

Revision ID: 5244349c0295
Revises: daad2f231ce8
Create Date: 2024-05-13 15:49:13.755081

"""

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5244349c0295"
down_revision = "daad2f231ce8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "building_info", sa.Column("power_indicators", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column("building_info", sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("building_info", "extra")
    op.drop_column("building_info", "power_indicators")
    # ### end Alembic commands ###
