"""update group

Revision ID: 85b9c4a015c1
Revises: 5244349c0295
Create Date: 2024-05-23 22:00:00.301029

"""

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = "85b9c4a015c1"
down_revision = "5244349c0295"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_group_description", table_name="group")
    op.drop_index("ix_group_id", table_name="group")
    op.drop_index("ix_group_name", table_name="group")
    op.create_unique_constraint(None, "group", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "group", type_="unique")
    op.create_index("ix_group_name", "group", ["name"], unique=True)
    op.create_index("ix_group_id", "group", ["id"], unique=False)
    op.create_index("ix_group_description", "group", ["description"], unique=True)
    # ### end Alembic commands ###
