version: "3.3"

services:
  term-management:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: term-management
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always
